# Generated by Django 4.0.4 on 2022-12-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listofrentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='img',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
