# Generated by Django 4.0.4 on 2022-12-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listofrentals', '0002_rental_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='img',
            field=models.TextField(),
        ),
    ]
