# Generated by Django 4.0.4 on 2022-12-09 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listofrentals', '0004_rental_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Verybad'), (2, 'Bad'), (3, 'Normal'), (4, 'Good'), (5, 'Verygood')])),
            ],
        ),
        migrations.AlterField(
            model_name='rental',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.CreateModel(
            name='RatingComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listofrentals.rating')),
            ],
        ),
        migrations.AddField(
            model_name='rental',
            name='rating',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='listofrentals.rating'),
        ),
    ]
