# Generated by Django 4.0.4 on 2022-12-09 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listofrentals', '0005_rating_alter_rental_slug_ratingcomment_rental_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingcomment',
            name='rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listofrentals.ratingcomment'),
        ),
    ]
