# Generated by Django 4.0.4 on 2022-12-09 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listofrentals', '0006_remove_ratingcomment_rating_rating_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='comment',
        ),
        migrations.AddField(
            model_name='ratingcomment',
            name='ratig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listofrentals.rating'),
        ),
    ]
