# Generated by Django 4.0.4 on 2022-12-09 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listofrentals', '0009_alter_ratingcomment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingcomment',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listofrentals.rating'),
        ),
    ]
