# Generated by Django 4.0.4 on 2022-12-09 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_initial'),
        ('listofrentals', '0010_alter_ratingcomment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingcomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.generaluser'),
        ),
    ]
