# Generated by Django 4.0.4 on 2022-12-01 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_generaluser_options_alter_generaluser_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneralUser',
        ),
    ]
